# Generated by Django 2.2.1 on 2019-05-26 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=140)),
                ('last_name', models.CharField(max_length=140)),
                ('born', models.DateField()),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.AddField(
            model_name='mymovie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed', to='moviesApp.Person'),
        ),
        migrations.AddField(
            model_name='mymovie',
            name='writers',
            field=models.ManyToManyField(blank=True, related_name='writing_credits', to='moviesApp.Person'),
        ),
    ]
